feat(GallerySlider): add new component
consta-design-system/react-slick-adapter pull request #1
Opened 2022-12-29 10:00 UTC by gizeasy

consta-design-system/uikit#2399

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-uikit.vercel.app/?path=/docs/common-develop-commits-style--page)

2022-12-29 12:15 UTC, gizeasy commented on src/hooks/useSlider/useSlider.tsx
> +  const [slider, setSlider] = useState<ReturnType<typeof tns> | null>(null);
можно воспользоваться `useMemo` и возвращать на изменение пропсов новый экцемпляр `TinySliderInstance`
а пробовал сам менять пропсы так чтобы пересоздавался `TinySliderInstance` нормально все орабаывает? не ломается галерея?
еще кажется что при пересоздании `TinySliderInstance` нужно старый десроить, возможно утечка будет происходить

2022-12-29 12:15 UTC, gizeasy commented on src/components/GallerySlider/GallerySliderControls/GallerySliderControls.tsx
> +import { Button } from '@consta/uikit/Button';
Думаю лучше посавлять кнопки по одельности, они все равно, также одавать класс позиционирования этих кнопок, чтоб можно было взять свою накинуть класс из библиоеки и она встала в нужное место

2022-12-29 12:15 UTC, gizeasy commented on src/components/GallerySlider/__mocks__/mock.data.ts
> +    image: 'https://4kwallpapers.com/images/walls/thumbs_2t/5894.jpg',
Положи каринки в проект

2022-12-29 12:15 UTC, gizeasy commented on src/components/GallerySlider/GallerySliderItem/GallerySliderItem.css
> +  height: 100%;
Сейчас item тянеся под высоту слайдера, надо это сделать модификацией, по умолчанию не тянуть, а чтоб контент сам толкал высоту

к тому же есть в `tiny-slider` свойство `Autoheight`  можно посмореть как оно работает и при включении этого свойсва только начинать тянуть контент под высоту родителя

2022-12-29 12:15 UTC, gizeasy commented on src/components/GallerySlider/GallerySliderItem/GallerySliderItem.tsx
> +import { Text } from '@consta/uikit/Text';
![image](https://user-images.githubusercontent.com/13190808/209940265-663471ed-2b01-4907-b919-858af61d4ac1.png)

изображение находися нсразными отсупами по сетке

2023-01-30 11:37 UTC, BagenovA requested changes

2023-01-30 11:37 UTC, BagenovA commented on src/adapters/reactSlickAdapter/__stand__/ReactSlickAdapter.dev.stand.mdx
> +Вы может использовать индикаторы по умолчанию, указать их тип и положение, а также переопределить и укзать свои собственные.
Исправить на: Вы можете использовать индикаторы по умолчанию, указать их тип и положение, а также переопределить и указать свои собственные.

2023-01-30 11:37 UTC, BagenovA commented on src/adapters/reactSlickAdapter/__stand__/ReactSlickAdapter.dev.stand.mdx
> +Позиция индикаторов задается через свойство `indicatorsPosition`, которое принимает значения `bottom` и `left`. По умолчанию `bottom`.
Исправить на: Позиция индикаторов задаётся через свойство `indicatorsPosition`, которое принимает значения `bottom` и `left`. Значение по умолчанию `bottom`.

2023-01-30 11:37 UTC, BagenovA commented on src/adapters/reactSlickAdapter/__stand__/ReactSlickAdapter.dev.stand.mdx
> +Чтобы выбрать один из них необходимо определить свойство `indicatorsType`.
Исправить на: Чтобы выбрать один из них, необходимо определить свойство `indicatorsType`.

2023-01-30 11:37 UTC, BagenovA commented on src/adapters/reactSlickAdapter/__stand__/ReactSlickAdapter.dev.stand.mdx
> +> Если вы используете тип `icon` или `image` необходимо указать свойство `items`, а также в случае необходимости геттеры `getItemIcon` и `getItemImage` для иконок и изображений соответсвенно.
Исправить на: Если вы используете тип `icon` или `image`, укажите свойство `items`, а также, при необходимости, геттеры `getItemIcon` и `getItemImage` для иконок и изображений соответственно.

2023-01-30 12:58 UTC, gizeasy commented on src/mixs/ReactSlick/ReactSlick.ts
> +import 'slick-carousel/slick/slick-theme.css';
<img width="849" alt="image" src="https://user-images.githubusercontent.com/13190808/215479479-151554e9-716b-4f13-92e6-749d1690d610.png">

тут чтото много лишнего, давай `slick-theme.css` вообще уберем. И напишем то что нужно в нашем адапере.

2023-01-30 12:58 UTC, gizeasy commented on src/adapters/reactSlickAdapter/__mocks__/mock.data.ts
> +    image: 'https://4kwallpapers.com/images/walls/thumbs_2t/5894.jpg',
Давай картинки в репозиторий положим. Сборка умеет с ними работать

`import imageSrc from '##/__mocks__/img1.jpg'`

`<img src={imageSrc}/>`

2023-01-30 12:58 UTC, gizeasy commented on src/mixs/ReactSlick/ReactSlick.css
> +        mask-image: url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTIiIGhlaWdodD0iMTIiIHZpZXdCb3g9IjAgMCAxMiAxMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZmlsbC1ydWxl
А что если перевернуть css`ом вторую стрелочку, чтоб меньше кода было?

2023-01-30 12:58 UTC, gizeasy commented on src/mixs/ReactSlick/ReactSlick.css
> +      right: var(--space-m);
` right: var(--space-m);`
тут точно такой отступ? 
просо у другой кнопки 
`left: var(--react-slick-left-button-offset);`

2023-01-30 12:58 UTC, gizeasy commented on src/adapters/reactSlickAdapter/__mocks__/mock.data.ts
> +    image: 'https://4kwallpapers.com/images/walls/thumbs_2t/5894.jpg',
и картинки давай одного размера  чтоб по красивие было

2023-01-30 12:58 UTC, gizeasy commented on src/stand/standConfig.ts
> +      initialOpen: true,
![image](https://user-images.githubusercontent.com/13190808/215483005-c1b5ec6d-7899-4e56-81dc-bcab20d3bfb6.png)

отсортируй группы, чтоб документация первая была

2023-01-30 12:58 UTC, gizeasy commented on src/stand/standConfig.ts
> +      initialOpen: true,
И еще нет группы для компонентов

2023-01-30 13:06 UTC, N1MBER commented on src/mixs/ReactSlick/ReactSlick.css
> +      right: var(--space-m);
Да, это нужно для того если индикаторы находятся не снизу, а слева

2023-01-31 07:28 UTC, gizeasy commented on src/mixs/ReactSlick/ReactSlick.css
> +
![image](https://user-images.githubusercontent.com/13190808/215687903-25790b10-a483-4e63-97c8-cb479c661be4.png)

2023-01-31 07:28 UTC, gizeasy commented on src/mixs/ReactSlick/ReactSlick.css
> +
Точечки))

2023-01-31 07:28 UTC, gizeasy commented on src/mixs/ReactSlick/__stand__/examples/ReactSlickExample/ReactSlickExample.tsx
> +import Image4 from '##/__mocks__/image4.jpeg';
Image4 с маленькой буквы, это не компонент и не тип там строка

2023-01-31 07:28 UTC, gizeasy commented on src/components/ReactSlickIndicator/__stand__/ReactSlickIndicator.dev.stand.mdx
> +| `image?`          | `'string`                           | -            | Картинка        |
`'string`  - пропусил  `'`

2023-01-31 07:28 UTC, gizeasy commented on src/components/ReactSlickControl/__stand__/ReactSlickControl.stand.tsx
> +  description: 'Контролы.',
Напиши по побробнее

2023-01-31 07:28 UTC, gizeasy commented on src/components/ReactSlickIndicator/__stand__/ReactSlickIndicator.stand.tsx
> +  description: 'Индикаторы.',
Напиши по подробнее

2023-01-31 07:28 UTC, gizeasy commented on src/components/ReactSlickIndicator/__stand__/ReactSlickIndicator.stand.mdx
> +```tsx
Может всю информацию перенесем в одну вкладку, ее не много

2023-01-31 07:28 UTC, gizeasy commented on src/components/ReactSlickControl/__stand__/ReactSlickControl.stand.mdx
> +import { ReactSlickControl } from '@consta/react-slick-adapter/ReactSlickControl';
Давай все перенесем в одну вкладку?

2023-01-31 07:28 UTC, gizeasy commented on src/stand/standConfig.ts
> +      id: 'adapters',
Адаперы выше думаю стоит вокнуть, сразу под быстрый старт

2023-01-31 08:35 UTC, merged

2023-01-31 13:44 UTC, BagenovA commented on src/components/ReactSlickIndicator/__stand__/ReactSlickIndicator.stand.tsx
> +  description: 'Индикатор, отрожающий позицию слайда.',
Изменить на: Индикатор позиции слайда

2023-01-31 13:48 UTC, BagenovA commented
В Быстром старте исправить опечатку в слове "карточек"